import { z } from 'zod';
import type { Account, Action, Position } from '@bolinha/core';
import type { MarketSnapshot } from '@bolinha/market-data';

const wireSchema = z.object({ acao: z.string(), valor_usdt: z.coerce.number().finite().nonnegative(), confianca: z.coerce.number().min(0).max(1), motivo: z.string().min(1).max(2000) });
export interface AiDecision { action: Action; amountUsdt: number; confidence: number; reason: string; rawResponse: string | null }
export interface AiUsage { modelRequested: string; modelReturned: string | null; promptTokens: number | null; completionTokens: number | null; totalTokens: number | null; costUsd: number | null; latencyMs: number; error: string | null; fallbackUsed: boolean }
const actionMap: Record<string, Action> = { BUY:'BUY', SELL:'SELL', HOLD:'HOLD', COMPRAR:'BUY', COMPRA:'BUY', VENDER:'SELL', VENDA:'SELL', WAIT:'HOLD', ESPERAR:'HOLD', AGUARDAR:'HOLD' };
export function parseAiContent(content: string | null | undefined): AiDecision { if(!content)return {action:'HOLD',amountUsdt:0,confidence:0,reason:'AI returned empty content',rawResponse:content??null}; try { const jsonMatch=content.match(/\{[\s\S]*\}/); const parsed=wireSchema.safeParse(JSON.parse(jsonMatch?.[0] ?? content)); if(!parsed.success)return {action:'HOLD',amountUsdt:0,confidence:0,reason:'Invalid AI response schema',rawResponse:content}; const action=actionMap[parsed.data.acao.trim().toUpperCase()]; if(!action)return {action:'HOLD',amountUsdt:0,confidence:0,reason:'Invalid AI action',rawResponse:content}; return {action,amountUsdt:parsed.data.valor_usdt,confidence:parsed.data.confianca,reason:parsed.data.motivo,rawResponse:content}; } catch { return {action:'HOLD',amountUsdt:0,confidence:0,reason:'Invalid AI JSON',rawResponse:content}; } }
export function buildPrompt(snapshot: MarketSnapshot, account: Account, position: Position | null): string { const permitted=position?'SELL ou HOLD':'BUY ou HOLD'; return `Você é um analista de sinais. Responda SOMENTE JSON: {"acao":"BUY|SELL|HOLD","valor_usdt":number,"confianca":0..1,"motivo":"..."}.\nContexto financeiro: banca inicial ${account.initialBankUsdt} USDT; caixa ${account.cashUsdt} USDT; posição ${position?`${position.quantity} BTC, custo ${position.costUsdt} USDT`:'nenhuma'}; patrimônio estimado calculado localmente. Ações permitidas agora: ${permitted}.\nSELL significa fechar integralmente a posição. Para SELL, valor_usdt não controla a quantidade vendida: o sistema vende 100% da posição conceitual, sujeito apenas às regras da Binance.\nUse exclusivamente os dados abaixo. Não invente notícias. Prefira HOLD sem sinal claro. Percentuais já estão em %, por exemplo -0.25 significa -0,25%, nunca -25%. Não recalcule comparações normalizadas; regras de risco são determinísticas e você não as controla.\nIndicadores normalizados e crus: ${JSON.stringify(snapshot)}`; }
export class OpenRouterClient { constructor(private key: string, private models: string[], private fetchFn: typeof fetch = fetch) {} async decide(prompt: string): Promise<{ decision: AiDecision; usage: AiUsage }> { let lastError='No model attempted'; for(const [index,model] of this.models.entries()){ const started=Date.now(); try { const response=await this.fetchFn('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${this.key}`},body:JSON.stringify({model,messages:[{role:'user',content:prompt}],temperature:0,response_format:{type:'json_object'}}),signal:AbortSignal.timeout(20_000)}); if(!response.ok) throw new Error(`OpenRouter HTTP ${response.status}`); const body=await response.json() as {model?:string;choices?:Array<{message?:{content?:string|null}}> ;usage?:{prompt_tokens?:number;completion_tokens?:number;total_tokens?:number;cost?:number}}; const decision=parseAiContent(body.choices?.[0]?.message?.content); if(decision.reason.startsWith('Invalid')||decision.reason==='AI returned empty content') throw new Error(decision.reason); return {decision,usage:{modelRequested:model,modelReturned:body.model??model,promptTokens:body.usage?.prompt_tokens??null,completionTokens:body.usage?.completion_tokens??null,totalTokens:body.usage?.total_tokens??null,costUsd:body.usage?.cost??null,latencyMs:Date.now()-started,error:null,fallbackUsed:index>0}}; } catch(error) { lastError=error instanceof Error?error.message:'Unknown AI error'; } } return {decision:{action:'HOLD',amountUsdt:0,confidence:0,reason:`All OpenRouter fallbacks failed: ${lastError}`,rawResponse:null},usage:{modelRequested:this.models.at(-1)??'none',modelReturned:null,promptTokens:null,completionTokens:null,totalTokens:null,costUsd:null,latencyMs:0,error:lastError,fallbackUsed:this.models.length>1}}; } }
