CREATE TABLE IF NOT EXISTS trading_account (id serial PRIMARY KEY, initial_bank_usdt numeric(20,8) NOT NULL, cash_usdt numeric(20,8) NOT NULL, realized_pnl_usdt numeric(20,8) NOT NULL DEFAULT 0, ai_cost_usd numeric(20,8) NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS positions (id serial PRIMARY KEY, symbol varchar(20) NOT NULL, quantity numeric(28,12) NOT NULL, entry_price numeric(28,12) NOT NULL, cost_usdt numeric(20,8) NOT NULL, status varchar(10) NOT NULL, opened_at timestamptz NOT NULL, closed_at timestamptz, realized_pnl_usdt numeric(20,8));
CREATE UNIQUE INDEX IF NOT EXISTS one_open_position ON positions(status) WHERE status='OPEN';
CREATE TABLE IF NOT EXISTS market_snapshots (id serial PRIMARY KEY, symbol varchar(20) NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS account_snapshots (id serial PRIMARY KEY, cash_usdt numeric(20,8) NOT NULL, equity_usdt numeric(20,8) NOT NULL, realized_pnl_usdt numeric(20,8) NOT NULL, unrealized_pnl_usdt numeric(20,8) NOT NULL, net_pnl_usdt numeric(20,8) NOT NULL, price numeric(28,12) NOT NULL, position_quantity numeric(28,12), position_cost_usdt numeric(20,8), created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS account_snapshots_created_at_idx ON account_snapshots(created_at);
CREATE TABLE IF NOT EXISTS orders (id serial PRIMARY KEY, client_order_id uuid UNIQUE NOT NULL, binance_order_id varchar(64), side varchar(4) NOT NULL, requested_amount numeric(20,8) NOT NULL, executed_quantity numeric(28,12), executed_quote_amount numeric(20,8), commission numeric(20,8), status varchar(20) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), executed_at timestamptz);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS requested_quantity numeric(28,12);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS reconciliation_reason text;
CREATE UNIQUE INDEX IF NOT EXISTS orders_binance_order_id_unique ON orders(binance_order_id) WHERE binance_order_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS trades (id serial PRIMARY KEY, order_id integer NOT NULL REFERENCES orders(id), position_id integer REFERENCES positions(id), side varchar(4) NOT NULL, quantity numeric(28,12) NOT NULL, quote_amount numeric(20,8) NOT NULL, commission numeric(20,8) NOT NULL DEFAULT 0, executed_at timestamptz NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS trades_order_id_unique ON trades(order_id);
CREATE TABLE IF NOT EXISTS order_fills (id serial PRIMARY KEY, order_id integer NOT NULL REFERENCES orders(id), trade_id varchar(64), price numeric(28,12) NOT NULL, quantity numeric(28,12) NOT NULL, commission numeric(28,12) NOT NULL, commission_asset varchar(20) NOT NULL, raw jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS order_fills_order_trade_id_unique ON order_fills(order_id,trade_id) WHERE trade_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS trade_fees (id serial PRIMARY KEY, trade_id integer NOT NULL REFERENCES trades(id), fill_id integer REFERENCES order_fills(id), asset varchar(20) NOT NULL, amount numeric(28,12) NOT NULL, amount_usdt numeric(20,8), created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS trade_fees_fill_id_unique ON trade_fees(fill_id) WHERE fill_id IS NOT NULL;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS net_quantity numeric(28,12);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS net_quote_amount numeric(20,8);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS gross_pnl_usdt numeric(20,8);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS fees_usdt_known numeric(20,8) NOT NULL DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS net_pnl_usdt numeric(20,8);
CREATE TABLE IF NOT EXISTS ai_decisions (id serial PRIMARY KEY, timestamp timestamptz NOT NULL DEFAULT now(), model_requested text NOT NULL, model_returned text, action_requested varchar(4) NOT NULL, action_after_risk varchar(4) NOT NULL, amount_requested numeric(20,8) NOT NULL, amount_after_risk numeric(20,8) NOT NULL, confidence double precision NOT NULL, reason text NOT NULL, raw_response text, rejection_reason text, market_snapshot_id integer REFERENCES market_snapshots(id));
CREATE TABLE IF NOT EXISTS ai_usage (id serial PRIMARY KEY, decision_id integer REFERENCES ai_decisions(id), model text NOT NULL, prompt_tokens integer, completion_tokens integer, total_tokens integer, cost_usd numeric(20,8), latency_ms integer NOT NULL, error text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS daily_results (id serial PRIMARY KEY, day timestamptz NOT NULL UNIQUE, equity_usdt numeric(20,8) NOT NULL, realized_pnl_usdt numeric(20,8) NOT NULL, unrealized_pnl_usdt numeric(20,8) NOT NULL);
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS session_day date;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS timezone varchar(64) NOT NULL DEFAULT 'America/Sao_Paulo';
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS initial_equity_usdt numeric(20,8);
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS final_equity_usdt numeric(20,8);
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS gross_return_pct numeric(20,8);
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS trade_count integer NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS buy_count integer NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS sell_count integer NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS hold_count integer NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS rejected_decision_count integer NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS ai_call_count integer NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS ai_cost_usd numeric(20,8) NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS models_used jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS fallback_count integer NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS error_count integer NOT NULL DEFAULT 0;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS forced_close_occurred boolean NOT NULL DEFAULT false;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS started_at timestamptz;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS finished_at timestamptz;
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS gross_pnl_usdt numeric(20,8);
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS fees_usdt_known numeric(20,8);
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS net_pnl_usdt numeric(20,8);
ALTER TABLE daily_results ADD COLUMN IF NOT EXISTS fees_by_asset jsonb;
CREATE UNIQUE INDEX IF NOT EXISTS daily_results_session_day_unique ON daily_results(session_day) WHERE session_day IS NOT NULL;
CREATE TABLE IF NOT EXISTS trading_sessions (session_day date PRIMARY KEY, timezone varchar(64) NOT NULL, phase varchar(32) NOT NULL, started_at timestamptz, finished_at timestamptz, last_cycle_at timestamptz, next_cycle_at timestamptz, cycles_today integer NOT NULL DEFAULT 0, updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE trading_sessions ADD COLUMN IF NOT EXISTS initial_equity_usdt numeric(20,8);
CREATE TABLE IF NOT EXISTS system_events (id serial PRIMARY KEY, level varchar(10) NOT NULL, event varchar(100) NOT NULL, message text NOT NULL, payload jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS worker_heartbeats (id serial PRIMARY KEY, worker_id varchar(100) NOT NULL, status varchar(10) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reconciliation_state (id boolean PRIMARY KEY DEFAULT true CHECK (id), status varchar(10) NOT NULL DEFAULT 'ERROR', state_consistent boolean NOT NULL DEFAULT false, last_reconciled_at timestamptz, last_error text, updated_at timestamptz NOT NULL DEFAULT now());
