export interface Candle { openTime: number; open: number; high: number; low: number; close: number; volume: number; closeTime: number }
export type Relation = 'EMA9_ABOVE_EMA21' | 'EMA9_BELOW_EMA21' | 'EMA_EQUAL';
export type RsiState = 'OVERBOUGHT' | 'OVERSOLD' | 'NEUTRAL';
export type ReturnState = 'UP' | 'DOWN' | 'FLAT';
export type VolumeState = 'HIGH' | 'NORMAL' | 'LOW';
export interface IndicatorSet { price: number; ema9: number; ema21: number; rsi14: number; return1: number; return3: number; return12: number; volume: number; volumeAvg20: number; volumeRatio: number; high20: number; low20: number; emaRelation: Relation; rsiState: RsiState; shortReturnState: ReturnState; volumeState: VolumeState }
export interface MarketSnapshot { symbol: string; capturedAt: string; intervals: Record<'1m' | '5m' | '15m', IndicatorSet> }
export function ema(values: number[], period: number): number { if (values.length < period) throw new Error(`Need ${period} candles`); const k = 2 / (period + 1); return values.slice(0, period).reduce((a,b)=>a+b,0) / period + values.slice(period).reduce((e,v)=>v*k+e*(1-k), values.slice(0,period).reduce((a,b)=>a+b,0) / period); }
export function rsi(values: number[], period = 14): number { if(values.length <= period) throw new Error('Need RSI candles'); let gains=0, losses=0; for(let i=values.length-period;i<values.length;i++){const d=values[i]-values[i-1]; gains+=Math.max(d,0); losses+=Math.max(-d,0);} if(losses===0) return 100; const rs=gains/losses; return 100-(100/(1+rs)); }
export function returnPercent(values: number[], periods: number): number { const current=values.at(-1)!; const previous=values.at(-(periods+1))!; return ((current-previous)/previous)*100; }
export function returnState(value: number): ReturnState { return value > 0.02 ? 'UP' : value < -0.02 ? 'DOWN' : 'FLAT'; }
export function calculateIndicators(candles: Candle[]): IndicatorSet { if(candles.length<22) throw new Error('At least 22 candles required'); const closes=candles.map(c=>c.close); const last=candles.at(-1)!; const last20=candles.slice(-20); const e9=ema(closes,9),e21=ema(closes,21), r=rsi(closes); const avg=last20.reduce((s,c)=>s+c.volume,0)/20; const ret=returnPercent(closes,1); return { price:last.close,ema9:e9,ema21:e21,rsi14:r,return1:ret,return3:returnPercent(closes,3),return12:returnPercent(closes,12),volume:last.volume,volumeAvg20:avg,volumeRatio: last.volume/avg,high20:Math.max(...last20.map(c=>c.high)),low20:Math.min(...last20.map(c=>c.low)),emaRelation:e9>e21?'EMA9_ABOVE_EMA21':e9<e21?'EMA9_BELOW_EMA21':'EMA_EQUAL',rsiState:r>=70?'OVERBOUGHT':r<=30?'OVERSOLD':'NEUTRAL',shortReturnState:returnState(ret),volumeState:last.volume/avg>1.3?'HIGH':last.volume/avg<0.7?'LOW':'NORMAL'}; }
export function makeSnapshot(symbol: string, candles: Record<'1m'|'5m'|'15m', Candle[]>): MarketSnapshot { return { symbol, capturedAt:new Date().toISOString(), intervals: { '1m':calculateIndicators(candles['1m']), '5m':calculateIndicators(candles['5m']), '15m':calculateIndicators(candles['15m']) } }; }
